# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eca03bcf27f5052738de87c235b6c0c45a0c3d4716c572f87af0186522595be9278523f8576d7288d9bbc38739189069ccfac44d24c3fe7479dbbf4be061dd2

test:
  secret_key_base: ed389b7e856e9ebad912e2d8ba269c0290bad237323d2d687fa9da5691363c330c59793269f08f664f600598341f4f21619f798dc60db19a1c25ff1a2bab9b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
